package ie.ncirl.sspproject.dataprocess.measurement.traceroute

import ie.ncirl.sspproject.dataprocess.measurement.DeviceProperties

case class TracerouteMeasurement
(
  task: Task,
  parameters: Parameters,
  success: String,
  timestamp: String,
  device_properties: DeviceProperties,
  values: Values,
  `type`: String,
  id: String
)

case class Task
(
  count: String,
  filter: String,
  parameters: TaskParameters,
  created: String,
  start_time: String,
  interval_sec: String,
  priority: String,
  tag: String,
  end_time: String,
  `type`: String,
  id: String
)

case class TaskParameters
(
  max_hop_count: String,
  target: String,
  pings_per_hop: String,
  profile_1_freq: String,
  profile_2_freq: String,
  profile_3_freq: String,
  profile_4_freq: String,
  profile_unlimited: String
)

case class Parameters
(
  count: String,
  ping_timeout_sec: String,
  parameters: String,
  start_time: String,
  ping_interval_sec: String,
  interval_sec: String,
  pings_per_hop: String,
  priority: String,
  packet_size_byte: String,
  ping_exe: String,
  key: String,
  target: String,
  max_hop_count: String,
  `type`: String,
  end_time: String,
  context_interval_sec: String,
  pre_condition: String,
  parallel_probe_num: String
)

case class Values
(
  hop_0_rtt_ms: String,
  hop_1_rtt_ms: String,
  hop_2_rtt_ms: String,
  hop_3_rtt_ms: String,
  hop_4_rtt_ms: String,
  hop_5_rtt_ms: String,
  hop_6_rtt_ms: String,
  hop_7_rtt_ms: String,
  hop_8_rtt_ms: String,
  hop_9_rtt_ms: String,
  hop_10_rtt_ms: String,
  hop_11_rtt_ms: String,
  hop_12_rtt_ms: String,
  hop_13_rtt_ms: String,
  hop_14_rtt_ms: String,
  hop_15_rtt_ms: String,
  hop_16_rtt_ms: String,
  hop_17_rtt_ms: String,
  hop_18_rtt_ms: String,
  hop_19_rtt_ms: String,
  hop_20_rtt_ms: String,
  hop_21_rtt_ms: String,
  hop_22_rtt_ms: String,
  hop_23_rtt_ms: String,
  hop_24_rtt_ms: String,
  hop_25_rtt_ms: String,
  hop_26_rtt_ms: String,
  hop_27_rtt_ms: String,
  hop_28_rtt_ms: String,
  hop_29_rtt_ms: String,
  hop_30_rtt_ms: String,

  hop_0_rtt_ms_1: String,
  hop_1_rtt_ms_1: String,
  hop_2_rtt_ms_1: String,
  hop_3_rtt_ms_1: String,
  hop_4_rtt_ms_1: String,
  hop_5_rtt_ms_1: String,
  hop_6_rtt_ms_1: String,
  hop_7_rtt_ms_1: String,
  hop_8_rtt_ms_1: String,
  hop_9_rtt_ms_1: String,
  hop_10_rtt_ms_1: String,
  hop_11_rtt_ms_1: String,
  hop_12_rtt_ms_1: String,
  hop_13_rtt_ms_1: String,
  hop_14_rtt_ms_1: String,
  hop_15_rtt_ms_1: String,
  hop_16_rtt_ms_1: String,
  hop_17_rtt_ms_1: String,
  hop_18_rtt_ms_1: String,
  hop_19_rtt_ms_1: String,
  hop_20_rtt_ms_1: String,
  hop_21_rtt_ms_1: String,
  hop_22_rtt_ms_1: String,
  hop_23_rtt_ms_1: String,
  hop_24_rtt_ms_1: String,
  hop_25_rtt_ms_1: String,
  hop_26_rtt_ms_1: String,
  hop_27_rtt_ms_1: String,
  hop_28_rtt_ms_1: String,
  hop_29_rtt_ms_1: String,
  hop_30_rtt_ms_1: String,

  hop_0_addr_1: String,
  hop_1_addr_1: String,
  hop_2_addr_1: String,
  hop_3_addr_1: String,
  hop_4_addr_1: String,
  hop_5_addr_1: String,
  hop_6_addr_1: String,
  hop_7_addr_1: String,
  hop_8_addr_1: String,
  hop_9_addr_1: String,
  hop_10_addr_1: String,
  hop_11_addr_1: String,
  hop_12_addr_1: String,
  hop_13_addr_1: String,
  hop_14_addr_1: String,
  hop_15_addr_1: String,
  hop_16_addr_1: String,
  hop_17_addr_1: String,
  hop_18_addr_1: String,
  hop_19_addr_1: String,
  hop_20_addr_1: String,
  hop_21_addr_1: String,
  hop_22_addr_1: String,
  hop_23_addr_1: String,
  hop_24_addr_1: String,
  hop_25_addr_1: String,
  hop_26_addr_1: String,
  hop_27_addr_1: String,
  hop_28_addr_1: String,
  hop_29_addr_1: String,
  hop_30_addr_1: String,

  hop_0_addr_2: String,
  hop_1_addr_2: String,
  hop_2_addr_2: String,
  hop_3_addr_2: String,
  hop_4_addr_2: String,
  hop_5_addr_2: String,
  hop_6_addr_2: String,
  hop_7_addr_2: String,
  hop_8_addr_2: String,
  hop_9_addr_2: String,
  hop_10_addr_2: String,
  hop_11_addr_2: String,
  hop_12_addr_2: String,
  hop_13_addr_2: String,
  hop_14_addr_2: String,
  hop_15_addr_2: String,
  hop_16_addr_2: String,
  hop_17_addr_2: String,
  hop_18_addr_2: String,
  hop_19_addr_2: String,
  hop_20_addr_2: String,
  hop_21_addr_2: String,
  hop_22_addr_2: String,
  hop_23_addr_2: String,
  hop_24_addr_2: String,
  hop_25_addr_2: String,
  hop_26_addr_2: String,
  hop_27_addr_2: String,
  hop_28_addr_2: String,
  hop_29_addr_2: String,
  hop_30_addr_2: String,

  hop_0_addr_3: String,
  hop_1_addr_3: String,
  hop_2_addr_3: String,
  hop_3_addr_3: String,
  hop_4_addr_3: String,
  hop_5_addr_3: String,
  hop_6_addr_3: String,
  hop_7_addr_3: String,
  hop_8_addr_3: String,
  hop_9_addr_3: String,
  hop_10_addr_3: String,
  hop_11_addr_3: String,
  hop_12_addr_3: String,
  hop_13_addr_3: String,
  hop_14_addr_3: String,
  hop_15_addr_3: String,
  hop_16_addr_3: String,
  hop_17_addr_3: String,
  hop_18_addr_3: String,
  hop_19_addr_3: String,
  hop_20_addr_3: String,
  hop_21_addr_3: String,
  hop_22_addr_3: String,
  hop_23_addr_3: String,
  hop_24_addr_3: String,
  hop_25_addr_3: String,
  hop_26_addr_3: String,
  hop_27_addr_3: String,
  hop_28_addr_3: String,
  hop_29_addr_3: String,
  hop_30_addr_3: String,

  CalledByLocation: String,
  num_hops: String,
  MeasurementLatitude: String,
  MeasurementLongitude: String,
  error: String,
  context_results: String
)

