package ie.ncirl.sspproject.dataprocess.measurement.dnslookup

import ie.ncirl.sspproject.dataprocess.measurement.DeviceProperties

case class DnsLookupMeasurement
(
  task: Task,
  parameters: Parameters,
  success: String,
  timestamp: String,
  device_properties: DeviceProperties,
  values: Values,
  `type`: String,
  id: String
)

case class Task
(
  count: String,
  filter: String,
  parameters: TaskParameters,
  created: String,
  start_time: String,
  interval_sec: String,
  priority: String,
  tag: String,
  end_time: String,
  `type`: String,
  id: String
)

case class TaskParameters
(
  target: String,
  server: String,
  profile_1_freq: String,
  profile_2_freq: String,
  profile_3_freq: String,
  profile_4_freq: String,
  profile_unlimited: String
)

case class Parameters
(
  count: String,
  target: String,
  parameters: String,
  start_time: String,
  interval_sec: String,
  server: String,
  priority: String,
  end_time: String,
  key: String,
  `type`: String,
  context_interval_sec: String,
  has_multi_server: String,
  servers: Array[String],
  sensitive: String,
  qclass: String,
  qtype: String
)

case class Values
(
  time_ms: String,
  CalledByLocation: String,
  MeasurementLatitude: String,
  real_hostname: String,
  address: String,
  MeasurementLongitude: String,
  error: String,
  context_results: String,
  qclass: String,
  qtype: String,
  results: String,
  target: String,
  rdata_0_0: String,
  rdata_0_1: String,
  rdata_0_2: String,
  rdata_0_3: String,
  rdata_0_4: String,
  rdata_0_5: String,
  name_0_0: String,
  name_0_1: String,
  name_0_2: String,
  name_0_3: String,
  name_0_4: String,
  name_0_5: String,
  respTime_0: String,
  respTime_1: String,
  respTime_2: String,
  respTime_3: String,
  respId_0: String,
  respId_1: String,
  respId_2: String,
  respId_3: String,
  qryId_0: String,
  qryId_1: String,
  qryId_2: String,
  qryId_3: String,
  rcode_0: String,
  rcode_1: String,
  rcode_2: String,
  rcode_3: String,
  qclass_0: String,
  qclass_1: String,
  qclass_2: String,
  qclass_3: String,
  payload_0: String,
  payload_1: String,
  payload_2: String,
  payload_3: String,
  qtype_0: String,
  qtype_1: String,
  qtype_2: String,
  qtype_3: String,
  domain_0: String,
  domain_1: String,
  domain_2: String,
  domain_3: String,
  rtype_0_0: String,
  rtype_0_1: String,
  rtype_0_2: String,
  rtype_0_3: String,
  rtype_0_4: String,
  rtype_0_5: String,
  tc_0: String,
  tc_1: String,
  tc_2: String,
  tc_3: String,
  server_0: String,
  server_1: String,
  server_2: String,
  server_3: String,
  isValid_0: String,
  isValid_1: String,
  isValid_2: String,
  isValid_3: String,
  answers_0: String,
  answers_1: String,
  answers_2: String,
  answers_3: String,
  queries: String,
  name_1_0: String,
  name_2_0: String,
  name_3_0: String,
  rdata_1_0: String,
  rdata_2_0: String,
  rdata_3_0: String,
  rtype_1_0: String,
  rtype_2_0: String,
  rtype_3_0: String,
  rtype_1_1: String,
  rtype_1_2: String,
  rtype_1_3: String,
  rtype_1_4: String,
  rtype_1_5: String,
  rdata_1_1: String,
  rdata_1_2: String,
  rdata_1_3: String,
  rdata_1_4: String,
  rdata_1_5: String,
  name_2_1: String,
  name_2_2: String,
  name_2_3: String,
  name_2_4: String,
  name_2_5: String,
  rdata_2_1: String,
  rdata_2_2: String,
  rdata_2_3: String,
  rdata_2_4: String,
  rdata_2_5: String,
  name_1_1: String,
  name_1_2: String,
  name_1_3: String,
  name_1_4: String,
  name_1_5: String,
  rtype_2_1: String,
  rtype_2_2: String,
  rtype_2_3: String,
  rtype_2_4: String,
  rtype_2_5: String,
  rtype_3_1: String,
  rtype_3_2: String,
  rtype_3_3: String,
  rtype_3_4: String,
  rtype_3_5: String,
  rdata_3_1: String,
  rdata_3_2: String,
  rdata_3_3: String,
  rdata_3_4: String,
  rdata_3_5: String,
  name_3_1: String,
  name_3_2: String,
  name_3_3: String,
  name_3_4: String,
  name_3_5: String
)

